"""Initial migration

Revision ID: 609ff745c231
Revises: 
Create Date: 2025-02-07 00:57:12.645382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609ff745c231'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuisine',
    sa.Column('cuisineID', sa.Integer(), nullable=False),
    sa.Column('cuisineName', sa.String(length=50), nullable=False),
    sa.Column('preferenceLevel', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('cuisineID')
    )
    op.create_table('menu',
    sa.Column('menuID', sa.Integer(), nullable=False),
    sa.Column('menuName', sa.String(length=100), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('menuID')
    )
    op.create_table('operating_hours',
    sa.Column('operatingHoursID', sa.Integer(), nullable=False),
    sa.Column('daysOfWeek', sa.String(length=62), nullable=True),
    sa.Column('openTime', sa.Time(), nullable=True),
    sa.Column('closeTime', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('operatingHoursID')
    )
    op.create_table('restaurant',
    sa.Column('restaurantID', sa.Integer(), nullable=False),
    sa.Column('restaurantName', sa.String(length=100), nullable=False),
    sa.Column('operatingHoursID', sa.Integer(), nullable=True),
    sa.Column('reviewID', sa.Integer(), nullable=True),
    sa.Column('dietaryRestrictions', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('ratingAverage', sa.SmallInteger(), nullable=True),
    sa.Column('phoneNumber', sa.String(length=14), nullable=True),
    sa.Column('menuID', sa.Integer(), nullable=True),
    sa.Column('cleanAverage', sa.SmallInteger(), nullable=True),
    sa.Column('busyAverage', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['menuID'], ['menu.menuID'], ),
    sa.ForeignKeyConstraint(['operatingHoursID'], ['operating_hours.operatingHoursID'], ),
    sa.ForeignKeyConstraint(['reviewID'], ['review.reviewID'], ),
    sa.PrimaryKeyConstraint('restaurantID')
    )
    op.create_table('review',
    sa.Column('reviewID', sa.Integer(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('imagePath', sa.Text(), nullable=True),
    sa.Column('dishID', sa.Integer(), nullable=True),
    sa.Column('restaurantID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dishID'], ['dish.dishID'], ),
    sa.ForeignKeyConstraint(['restaurantID'], ['restaurant.restaurantID'], ),
    sa.PrimaryKeyConstraint('reviewID')
    )
    op.create_table('saved_dishes',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('dishID', sa.Integer(), nullable=False),
    sa.Column('dateSaved', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dishID'], ['dish.dishID'], ),
    sa.ForeignKeyConstraint(['userID'], ['user.userID'], ),
    sa.PrimaryKeyConstraint('userID', 'dishID')
    )
    op.create_table('saved_restaurants',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('restaurantID', sa.Integer(), nullable=False),
    sa.Column('dateSaved', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurantID'], ['restaurant.restaurantID'], ),
    sa.ForeignKeyConstraint(['userID'], ['user.userID'], ),
    sa.PrimaryKeyConstraint('userID', 'restaurantID')
    )
    op.create_table('taste_buddies',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('buddyID', sa.Integer(), nullable=False),
    sa.Column('dateAdded', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buddyID'], ['user.userID'], ),
    sa.ForeignKeyConstraint(['userID'], ['user.userID'], ),
    sa.PrimaryKeyConstraint('userID', 'buddyID')
    )
    op.create_table('user',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=20), nullable=False),
    sa.Column('lastName', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('tasteBuddiesID', sa.Integer(), nullable=True),
    sa.Column('savedRestaurantsID', sa.Integer(), nullable=True),
    sa.Column('tasteProfileID', sa.Integer(), nullable=True),
    sa.Column('reviewID', sa.Integer(), nullable=True),
    sa.Column('savedDishesID', sa.Integer(), nullable=True),
    sa.Column('userRole', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['reviewID'], ['review.reviewID'], ),
    sa.ForeignKeyConstraint(['savedDishesID'], ['saved_dishes.userID'], ),
    sa.ForeignKeyConstraint(['savedRestaurantsID'], ['saved_restaurants.userID'], ),
    sa.ForeignKeyConstraint(['tasteBuddiesID'], ['taste_buddies.userID'], ),
    sa.ForeignKeyConstraint(['tasteProfileID'], ['taste_profile.tasteProfileID'], ),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('email')
    )
    op.create_table('taste_profile',
    sa.Column('tasteProfileID', sa.Integer(), nullable=False),
    sa.Column('dietaryRestrictions', sa.Text(), nullable=True),
    sa.Column('sweet', sa.SmallInteger(), nullable=True),
    sa.Column('salty', sa.SmallInteger(), nullable=True),
    sa.Column('sour', sa.SmallInteger(), nullable=True),
    sa.Column('bitter', sa.SmallInteger(), nullable=True),
    sa.Column('umami', sa.SmallInteger(), nullable=True),
    sa.Column('cuisineID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cuisineID'], ['cuisine.cuisineID'], ),
    sa.PrimaryKeyConstraint('tasteProfileID')
    )
    op.create_table('dish',
    sa.Column('dishID', sa.Integer(), nullable=False),
    sa.Column('dishTasteProfileID', sa.Integer(), nullable=True),
    sa.Column('dishName', sa.String(length=50), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dishTasteProfileID'], ['taste_profile.tasteProfileID'], ),
    sa.PrimaryKeyConstraint('dishID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dish')
    op.drop_table('taste_profile')
    op.drop_table('user')
    op.drop_table('taste_buddies')
    op.drop_table('saved_restaurants')
    op.drop_table('saved_dishes')
    op.drop_table('review')
    op.drop_table('restaurant')
    op.drop_table('operating_hours')
    op.drop_table('menu')
    op.drop_table('cuisine')
    # ### end Alembic commands ###
